### ISSUE TITLE
US1.3 Task1: Hashin Passwords

### ISSUE THREAD

**Issue by AlejandroDS1** [UB-ES-2024-A4/book-hub#123]
## Objectives
We want to hash passwords in our database so passwords are secure and private during a possible data leak.

## Tasks
- [x] Integrate `bcrypt` secure hashing library.
- [x] Implement password hashing during user registration.
- [x] Implement password verification during login.
- [x] Add unit and integration tests for hashing and authentication flows.
