### ISSUE TITLE
US1.4-Task4: Perform PreProduction deployment workflow and configuration for frontend.

### ISSUE THREAD

**Issue by AlejandroDS1** [UB-ES-2024-A4/book-hub#156]
# Tasks
- [x] Create a new Azure Web App.
- [x] Configure worflows to automatically deploy the app in PreProduction
- [x] Configure environment to deploy app
