### ISSUE TITLE
US1.4-Task5: Perform PreProduction deployment workflow and configuration for backend.

### ISSUE THREAD

**Issue by AlejandroDS1** [UB-ES-2024-A4/book-hub#158]
# Tasks
- [x] Create a new Azure Web App.
- [x] Configure worflows to automatically deploy the app in PreProduction
- [x] Configure environment to deploy app
