### ISSUE TITLE
US1.4-Task6: Implement tests badges to see tests performance from README.md

### ISSUE THREAD

**Issue by AlejandroDS1** [UB-ES-2024-A4/book-hub#160]
# Tasks
- [x] Configure pylint to static code test backend code
- [x] Create pylint badge and show it in README.md
- [x] Create pytest badge and show it in README.md
- [x] Make it run in PreProduction branch
