### ISSUE TITLE
US3.1 - Test 1: Unit Tests for Post API

### ISSUE THREAD

**Issue by gmarvega** [UB-ES-2024-A4/book-hub#34]
## Description
Develop unit tests for the Post entity API to ensure that all the endpoints functions correctly and handles all specified edge cases. This testing will help identify any bugs or unexpected behaviors in all actions to handle posts.

## Edge cases
Empty database
Invalid or missing query parameters
Missing post
Missing book
Missing user

## Tasks

- [x] Create endpoint tests
- [x] All read enpoints tests
- [x] Update endpoint tests
- [x] Delete endpoint tests

 
All tests return expected results, such as appropriate HTTP status codes, accurate data responses, and clear error messages where applicable.
